### ISSUE TITLE
App gettting crashed on android on final step

### ISSUE THREAD

**Issue by aliwaqar981** [GetStream/stream-video-js#1587]
**Which package/packages do you use?**

- [ ] `@stream-io/video-react-native-sdk`

**Describe the bug**
```
  useEffect(() => {
    const _call = client?.call('default', callId);
    _call
      ?.join({create: true})
      .then(() => {
        console.log("Call created successfully");
        
        setCall(_call) //App gets crashed when I set _call in state
      })
  }, [client, callId]);
```

I tried following the guideline for react native but in the end when I set call in state. App is getting crashed.

**To Reproduce**
Attaching a repo which might help in reproduction:
https://github.com/aliwaqar981/GetStreamRePro

 I tried to create reproduction in separate project. It was working correctly there. My new project was on react-native 0.76.2. I'm thinking maybe that's the reason but I'm not sure.

**Expected behavior**
Video call should get starts after running above code snippet.

**Screenshots**

**Version**

- SDK version
- "@stream-io/video-react-native-sdk": "^1.3.5",
- @stream-io/react-native-webrtc: ^124.0.2

**Env:**

Fill out what's applicable

**React Native**
react-native: 0.74.3

- OS: android
- Device or emulator: Vivo v21e

**Node JS client**

- Node version 20.12.0

**Additional context**
It seems some compatibility issue of sdk with react-native 0.74.3 because it worked on 0.76.2.

**Comment by aliwaqar981** [comment]
@oliverlaz There is not much in stack trace as I can't see any error and app get crashed. Although I'm attaching a video of crash and a log statement which I got. 

Logs:
`{"types": [64, 128]}`

**Video Recording**
https://github.com/user-attachments/assets/389718ba-e909-4b82-bbc4-9f40e526c43e

**Comment by aliwaqar981** [comment]
Hey @oliverlaz, Hi I've made a repository to produce the issue. It would be great if you can have a look:
https://github.com/aliwaqar981/GetStreamRePro.

**Comment by aliwaqar981** [comment]
There is one discovery that app is crashing even on latest version (`0.76.3`) of react-native. It's working in one of my repo which I have created initially but while testing I've created a new project and it gave me same crash that I found on react-native `0.74.3`

**Comment by oliverlaz** [comment]
hi @aliwaqar981, thank you for taking the time to prepare a repro app! It made everything easier.

Upon running your sample app, I managed to reproduce the crash. The error message attached to it was the following:
```
This app has crashed because it attempted to access privacy-sensitive data without a usage description. 
The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.
```

Upon providing the permission information in `Info.plist` as described below, the app worked as expected and was able to join the call.
- https://getstream.io/video/sdk/react-native/tutorial/video-calling/#step-2-install-the-sdk-and-declare-permissions

To fix the crash, open the `ios/SpaceMobile/Info.plist` and add the following lines:
```xml
<key>NSCameraUsageDescription</key>
<string>$(PRODUCT_NAME) would like to use your camera</string>
<key>NSMicrophoneUsageDescription</key>
<string>$(PRODUCT_NAME) would like to use your microphone</string>
```

Please let me know if this fixes the issue for you.

**Comment by aliwaqar981** [comment]
Hi @oliverlaz I did tested only on android but these android permissions are already added in my manifest file. Please see here:
https://github.com/aliwaqar981/GetStreamRePro/blob/main/android/app/src/main/AndroidManifest.xml

**Comment by oliverlaz** [comment]
hi @aliwaqar981, I'm sorry! I've somehow missed your last comment.
Before I dive in, do you still have the issue you originally described?

**Comment by salonitailor17** [comment]
Hello @all, I'm also getting the same issue. When the call is set in state, that time app is getting crashed. Any update on this, or has anyone found the solution for it? Here is the reference of the issue.


https://github.com/user-attachments/assets/194439d2-11cc-485d-a65b-ae4ee05a70cb

**Comment by salonitailor17** [comment]
Hello @oliverlaz and @haleemaMaqsood2, I'm also getting this same error.

![Image](https://github.com/user-attachments/assets/1db256e6-8f26-4e34-8b84-cbb4bb70a599)

Step to reproduce:

1. Run on a RN 0.73.6
2. Upgrade @stream-io/video-react-native-sdk to 1.9.2 and @stream-io/react-native-webrtc to 125.0.3
3. Run on Android and try to join the call

**Comment by kristian-mkd** [comment]
Hi @salonitailor17, can you try bumping the @stream-io/video-react-native-sdk to 1.9.8? This should fix the reported issue.

**Comment by salonitailor17** [comment]
Hi @kristian-mkd,

I've updated to the latest version (1.9.8) of @stream-io/video-react-native-sdk, and the **setPictureInPictureParams** issue is resolved. However, my app is still crashing after joining a call.

**Comment by santhoshvai** [comment]
@salonitailor17 can you share the stack trace of your crash please, this could be from foreground service types missing I think

**Comment by haleemaMaqsood2** [comment]
@kristian-mkd after updating to this version @stream-io/video-react-native-sdk to 1.9.8
My app also crash immediately after i join video call

**Comment by haleemaMaqsood2** [comment]
> [@haleemaMaqsood2](https://github.com/haleemaMaqsood2) can you share more details about the crash? like the code snippet it causes the crash, the stack trace and information about which lib versions are used, etc...

My Package.json dependies section
` "dependencies": {
    "@notifee/react-native": "^9.1.8",
    "@react-native-community/netinfo": "^11.4.1",
    "@stream-io/react-native-webrtc": "^125.0.3",
    "@stream-io/video-react-native-sdk": "^1.9.9",
    "react": "18.2.0",
    "react-native": "0.74.1",
    "react-native-incall-manager": "^4.2.0",
    "react-native-svg": "^15.11.1"
  },`

**Comment by santhoshvai** [comment]
@haleemaMaqsood2 please share your android native logs.. that will have the stack trace of your crash

**Comment by gdalkesh** [comment]
Hello @santhoshvai  and @kristian-mkd, I'm encountering the same issue where the app crashes when I attempt to join the call. I'm following the code from this [repository](https://github.com/GetStream/stream-tutorial-projects/tree/main/ReactNative/NativeCall) and have tested with dummy users using your Client & Authentication credentials.

Here are the library versions I'm using:

1. "react-native": "0.73.6"
2. "@stream-io/react-native-webrtc": "^125.0.4"
3. "@stream-io/video-react-native-sdk": "^1.9.16"
4. "@notifee/react-native": "^9.1.3"
I'm also sharing the native side stack trace for your reference.

Here's the [text file I uploaded](https://github.com/gdalkesh/example/blob/main/stacktrace).

**Comment by santhoshvai** [comment]
@gdalkesh I understand the issue now, you must be having notifee installed in your app. And that means the SDK will keep the call alive automatically, can you please follow the [keeping-call-alive](https://getstream.io/video/docs/react-native/core/keeping-call-alive/) documentation for React Native, following those steps will make sure that this crash wont happen

**Comment by gdalkesh** [comment]
Hello @santhoshvai,  

I followed the [[Keeping Call Alive](https://getstream.io/video/docs/react-native/core/keeping-call-alive/)](https://getstream.io/video/docs/react-native/core/keeping-call-alive/) guide, and it worked perfectly. I suggest updating the documentation accordingly if possible.  

Thanks!

**Comment by santhoshvai** [comment]
Thank you @gdalkesh we will look into a solution where the SDK can warn if configuration was not done to keep call alive and avoid it.
